{% set version = "1.0.2" %}
{% set sha256 = "7885092b2b96bf189c3a705cc3c412a4472ec5e8382d0b47219a66cccae73cfa" %}

package:
  name: jupyterlab_widgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - jupyter-packaging

  run:
    - python >=3.6

test:
  imports:
    - jupyterlab_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  summary: JupyterLab extension providing HTML widgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - jtpio
