{% set version = "3.0.4" %}

package:
  name: jupyterlab_widgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-{{ version }}.tar.gz
  sha256: 9a568e022b8bb53ab23291f6ddb52f8002b789c2c5763378cbc882be1d619be8
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - jupyter-packaging

  run:
    - python >=3.7

  run_constrained:
    - jupyterlab >=3,<4

test:
  imports:
    - jupyterlab_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  summary: JupyterLab extension providing HTML widgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
    - jtpio
    - bollwyvl
